const words = {
    "unidad_1": {
        "la cena": "вечеря",
        "el cine": "кино",
        "el zumo": "сок",
        "la verdad": "истина",
        "el/la estudiante": "ученичка/студентка",
        "el paĨs": "държава",
        "la lengua": "език",
        "el chico": "момче",
        "la chica": "момиче",
        "el amigo": "приятел",
        "la amiga": "приятелка",
        "la gente": "хора",
        "la calle": "улица",
        "la ciudad": "град",
        "el libro": "книга/учебник",
        "la plaza": "площад",
        "el coche": "кола",
        "el lápiz": "молив",
        "el zapato": "обувка",
        "el edificio": "сграда",
        "el bolso": "дамска чанта",
        "el jardin": "градина",
        "la vida": "живот",
        "la casa": "къща",
        "el gato": "котка",
        "el niño": "дете момче",
        "la niña": "дете момиче",
        "la luz": "светлина",
        "el pez": "риба",
        "la piel": "кожа",
        "amable": "любезен/а",
        "grosero/a": "груб/а",
        "agradable": "приятен/а"
        "desagradable": "неприятен/а",
        "guapo/a": "хубав/а",
        "feo/a": "грозен/а",
        "bonito/a": "хубав/а",
        "rubio/a": "рус/а",
        "moreno/a": "тъмнокос/а",
        "alto/a": "висок/а",
        "bajo/a": "нисък/а",
        "majo/a": "симпатичен/а",
        "antipático/a": "антипатичен/а",
        "delgado/a": "слаб/а",
        "gordo/a": "дебел/а",
        "simpático/a": "симпатичен/а",
        "antipático/a": "антипатичен/а",
        "cordial": "сърдечен/а",
        "distante": "дистанциран/а",
        "abierto/a": "общителен/а отворен/а",
        "cerrado/a": "затворен/а",
        "activo/a": "активен/а",
        "perezoso/a": "мързелив/а",
        "alegre": "весел/а",
        "triste": "тъжен/а",
        "inteligente": "интелигентен/а",
        "ignorante": "невеж/а",
        "listo/a": "умен/а готов/а",
        "tonto/a": "глупав/а",
        "gracioso/a": "забавен/а",
        "soso/a": "блудкав/а безличен/а",
        "divertado/a": "забавен/а",
        "abburido/a": "скучен/а",
        "sociable": "общителен/а",
        "cerrado/a": "затворен/а",
        "optimista": "оптимист",
        "pesimista": "песимист",
        "serio/a": "сериозен/а",
        "alegre": "весел/а",
        "rico/a": "богат/а",
        "pobre": "беден/а",
        "joven": "млад/а",
        "mayor": "възрастен/а",
        "nuevo/a": "нов/а",
        "viejo/a": "стар/а",
        "tranquilo/a": "спокоен/а",
        "nervioso/a": "нервен/а",
        "ancho/a": "широк/а",
        "estrecho/a": "тестн/а",
        "interesante": "интерестн/а",
        "aburrido/a": "скучен/а",
        "cómodo/a": "удобен/а",
        "incómodo/a": "неудобен/а",
        "económico/a": "икономичен/а",
        "caro/a": "скъп/а",
        "esbelto/a": "строен/а",
        "rechoncho/a": "трътлест/а",
        "duro/a": "твърд/а",
        "blando/a": "мек/а",
        "grande": "голям/а",
        "pequeño/a": "малък/а",
        "moderno/a": "модерен/а",
        "antiguo/a": "античен/а",
        "fuerte": "силен/а",
        "débil": "слаб/а",
        "extranjero/a": "чужденец/ка",
        "nativo/a": "местен/а",
        "bueno/a": "добър/а",
        "malo/a": "лош/а",
        "caro/a": "скъп/а",
        "barato/a": "евтин/а"
    }
};
